# Stage 1: Build the React app
FROM node:16 AS build

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend/ ./
EXPOSE 3000
CMD ["npm", "start"]

# RUN npm start

# # Stage 2: Serve the React app
# FROM nginx:alpine

# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
