version: '2.4' 

services:

  mongo:
    image: mongo
    ports:
      - "27018:27018"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/user  # Corrected indentation
    depends_on:
      - mongo
    ports:
      - "5000:5000"
